/** DEV-ONLY offline fixture hook.
 *
 *  In every committed build this is `null` and SupabaseService behaves exactly
 *  as before. The `offline` build configuration (angular.json) file-replaces
 *  this module with `offline-fixture.local.ts` — a gitignored file generated by
 *  tools/make-offline-fixture.mjs from one archived analysis row — so a local
 *  server can render a full run without touching the live database.
 *
 *  The production configuration never references the .local file, so the
 *  fixture cannot reach a production bundle. */
export interface OfflineFixture {
  /** `stocks` row, as getStockByTicker returns it. */
  stock: Record<string, unknown> & { id: string; ticker: string };
  /** `stock_analyses` row in the shape getAnalysis selects (before cleaning). */
  analysis: Record<string, unknown>;
  /** raw_output per module key ('political', 'price', … 'fs'). */
  chains: Record<string, unknown>;
  /** citation_refs rows ({module, refs}) for the analysis run date. */
  citationRows: unknown[];
}

export const OFFLINE_FIXTURE: OfflineFixture | null = null;
