import { OfflineFixture } from './offline-fixture.model';

/** DEV-ONLY offline fixture hook.
 *
 *  In every committed build this is `null` and SupabaseService behaves exactly
 *  as before. The `offline` build configuration (angular.json) file-replaces
 *  this module with `offline-fixture.local.ts` — a gitignored file generated by
 *  tools/make-offline-fixture.mjs from one archived analysis row — so a local
 *  server can render a full run without touching the live database.
 *
 *  The production configuration never references the .local file, so the
 *  fixture cannot reach a production bundle. */
export type { OfflineFixture };

export const OFFLINE_FIXTURE: OfflineFixture | null = null;
