import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { MarkdownService } from '../services/markdown.service';
import { CitationIndex } from '../services/citations';

/** Renders AI-generated analysis markdown to safe HTML for [innerHTML].
 *
 *  Usage: [innerHTML]="text | md"                              — markdown only
 *         [innerHTML]="text | md : ticker"                     — + factor cross-links
 *         [innerHTML]="text | md : ticker : factorSlug"        — exclude self-links
 *         [innerHTML]="text | md : ticker : slug : citations"  — + [1] citations
 *
 *  bypassSecurityTrustHtml is safe here because MarkdownService HTML-escapes
 *  the ENTIRE source before parsing — the only live HTML in the output is
 *  generated by the renderer itself, never by the model. Citation hrefs are
 *  built from the refs map only (services/citations.ts), and restricted to
 *  http(s); the models never supply URLs. */
@Pipe({ name: 'md', standalone: false, pure: true })
export class MdPipe implements PipeTransform {
  constructor(
    private markdown: MarkdownService,
    private sanitizer: DomSanitizer,
  ) {}

  transform(
    value: string | null | undefined,
    ticker?: string,
    currentFactor?: string,
    citations?: CitationIndex | null,
  ): SafeHtml {
    return this.sanitizer.bypassSecurityTrustHtml(
      this.markdown.render(value, { ticker, currentFactor, citations }),
    );
  }
}
