import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { MarkdownService } from '../services/markdown.service';

/** Renders AI-generated analysis markdown to safe HTML for [innerHTML].
 *
 *  Usage: [innerHTML]="text | md"                       — markdown only
 *         [innerHTML]="text | md : ticker"              — + factor cross-links
 *         [innerHTML]="text | md : ticker : factorSlug" — exclude self-links
 *
 *  bypassSecurityTrustHtml is safe here because MarkdownService HTML-escapes
 *  the ENTIRE source before parsing — the only live HTML in the output is
 *  generated by the renderer itself, never by the model. */
@Pipe({ name: 'md', standalone: false, pure: true })
export class MdPipe implements PipeTransform {
  constructor(
    private markdown: MarkdownService,
    private sanitizer: DomSanitizer,
  ) {}

  transform(value: string | null | undefined, ticker?: string, currentFactor?: string): SafeHtml {
    return this.sanitizer.bypassSecurityTrustHtml(
      this.markdown.render(value, { ticker, currentFactor }),
    );
  }
}
